/**
 * Encryption utilities for securing sensitive data.
 * Uses AES-256-GCM with PBKDF2 key derivation for robust protection.
 * This ensures that stored secrets or sensitive strings are encrypted at rest.
 */
import crypto from 'crypto';

// Configuration constants for the encryption algorithm to maintain consistency.
const ALGORITHM = 'aes-256-gcm'; // Galois/Counter Mode provides both authenticated encryption and data integrity.
const IV_LENGTH = 16; // Initialization Vector length (16 bytes is standard for AES).
const SALT_LENGTH = 64; // Length of the salt to ensure unique key derivation per encryption.
const TAG_LENGTH = 16; // Length of the authentication tag used by GCM mode.
const KEY_LENGTH = 32; // Standard 256-bit (32 byte) key length for AES-256.
const ITERATIONS = 100000; // Number of iteration for PBKDF2 (higher means more secure against brute-force attacks).

// The master secret used as the base for key derivation.
// Should securely be read from environment variables to prevent hardcoding sensitive secrets.
const MASTER_SECRET =
  process.env.BETTER_AUTH_SECRET || 'architect-vault-genesis-secret-key-32ch';

/**
 * Encrypts a plain text string into a secure base64 format.
 * Resulting format: base64(salt + iv + tag + encrypted_data)
 *
 * @param text The plain text string that needs to be encrypted.
 * @returns A base64 encoded string containing the encrypted data alongside necessary parameters for decryption.
 */
export function encrypt(text: string): string {
  // Generate random bytes for Initialization Vector to ensure the same plaintext encrypts to a different ciphertext each time.
  const iv = crypto.randomBytes(IV_LENGTH);
  // Generate random salt to be used during key derivation.
  const salt = crypto.randomBytes(SALT_LENGTH);

  // Derive a unique encryption key for this specific payload using PBKDF2 algorithm to resist dictionary attacks.
  const key = crypto.pbkdf2Sync(
    MASTER_SECRET, // The global base secret
    salt, // Unique salt for this operation
    ITERATIONS, // Work factor
    KEY_LENGTH, // Required length of the derived key
    'sha512' // Hashing algorithm used in PBKDF2
  );

  // Initialize the encryption cipher using the specified algorithm, derived key, and random IV.
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);

  // Perform the encryption on the plaintext and compile the resulting Buffer.
  const encrypted = Buffer.concat([
    cipher.update(text, 'utf8'), // Update cipher with utf8 plain text
    cipher.final(), // Finalize the encryption process
  ]);

  // Extract the GCM authentication tag, which ensures the data is not tampered with.
  const tag = cipher.getAuthTag();

  // Concatenate the salt, IV, auth tag, and encrypted data into one continuous buffer, then convert to a Base64 string for storage/transmission.
  return Buffer.concat([salt, iv, tag, encrypted]).toString('base64');
}

/**
 * Decrypts a previously encrypted string back to plain text.
 *
 * @param encryptedData The base64 encoded string generated by the `encrypt` function.
 * @returns The original decrypted plain text.
 * @throws Error if decryption fails (e.g., incorrect password, tampered data, or invalid format).
 */
export function decrypt(encryptedData: string): string {
  // Convert the base64 string back into a raw binary buffer.
  const buffer = Buffer.from(encryptedData, 'base64');

  // Extract the parameters from the combined buffer based on predefined lengths.
  const salt = buffer.subarray(0, SALT_LENGTH); // First 64 bytes is the salt
  const iv = buffer.subarray(SALT_LENGTH, SALT_LENGTH + IV_LENGTH); // Next 16 bytes is the IV
  const tag = buffer.subarray(
    SALT_LENGTH + IV_LENGTH,
    SALT_LENGTH + IV_LENGTH + TAG_LENGTH
  ); // Next 16 bytes is the Auth Tag
  const encrypted = buffer.subarray(SALT_LENGTH + IV_LENGTH + TAG_LENGTH); // The remainder of the buffer is the actual ciphertext

  // Re-derive the exact decryption key using the extracted salt and the original parameters.
  const key = crypto.pbkdf2Sync(
    MASTER_SECRET, // Global base secret
    salt, // Extracted salt
    ITERATIONS,
    KEY_LENGTH,
    'sha512'
  );

  // Initialize the decryption decipher using the same algorithm, re-derived key, and extracted IV.
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);

  // Set the extracted authentication tag to verify data integrity before decryption.
  decipher.setAuthTag(tag);

  // Perform the decryption and compile the resulting plain text Buffer.
  const decrypted = Buffer.concat([
    decipher.update(encrypted), // Update decipher with ciphertext
    decipher.final(), // Finalize decryption (will throw if auth tag validation fails)
  ]);

  // Convert the decrypted raw bytes back into a human-readable utf8 string.
  return decrypted.toString('utf8');
}
