export interface CityData {
  city: string;
  country: string;
  timezone: string;
}

export const cities: CityData[] = [
  { city: "Dhaka", country: "Bangladesh", timezone: "Asia/Dhaka" },
  { city: "New York", country: "United States", timezone: "America/New_York" },
  { city: "London", country: "United Kingdom", timezone: "Europe/London" },
  { city: "Tokyo", country: "Japan", timezone: "Asia/Tokyo" },
  { city: "Dubai", country: "United Arab Emirates", timezone: "Asia/Dubai" },
  { city: "Singapore", country: "Singapore", timezone: "Asia/Singapore" },
  { city: "Sydney", country: "Australia", timezone: "Australia/Sydney" },
  { city: "Paris", country: "France", timezone: "Europe/Paris" },
  { city: "Berlin", country: "Germany", timezone: "Europe/Berlin" },
  { city: "Moscow", country: "Russia", timezone: "Europe/Moscow" },
  { city: "Mumbai", country: "India", timezone: "Asia/Kolkata" },
  { city: "Delhi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Los Angeles", country: "United States", timezone: "America/Los_Angeles" },
  { city: "Chicago", country: "United States", timezone: "America/Chicago" },
  { city: "Toronto", country: "Canada", timezone: "America/Toronto" },
  { city: "Vancouver", country: "Canada", timezone: "America/Vancouver" },
  { city: "Beijing", country: "China", timezone: "Asia/Shanghai" },
  { city: "Hong Kong", country: "China", timezone: "Asia/Hong_Kong" },
  { city: "Seoul", country: "South Korea", timezone: "Asia/Seoul" },
  { city: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul" },
  { city: "Cairo", country: "Egypt", timezone: "Africa/Cairo" },
  { city: "Lagos", country: "Nigeria", timezone: "Africa/Lagos" },
  { city: "Johannesburg", country: "South Africa", timezone: "Africa/Johannesburg" },
  { city: "Sao Paulo", country: "Brazil", timezone: "America/Sao_Paulo" },
  { city: "Mexico City", country: "Mexico", timezone: "America/Mexico_City" },
  { city: "Buenos Aires", country: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { city: "Riyadh", country: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { city: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok" },
  { city: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta" },
  { city: "Manila", country: "Philippines", timezone: "Asia/Manila" },
  { city: "Melbourne", country: "Australia", timezone: "Australia/Melbourne" },
  { city: "Auckland", country: "New Zealand", timezone: "Pacific/Auckland" },
  { city: "Zurich", country: "Switzerland", timezone: "Europe/Zurich" },
  { city: "Amsterdam", country: "Netherlands", timezone: "Europe/Amsterdam" },
  { city: "Brussels", country: "Belgium", timezone: "Europe/Brussels" },
  { city: "Vienna", country: "Austria", timezone: "Europe/Vienna" },
  { city: "Madrid", country: "Spain", timezone: "Europe/Madrid" },
  { city: "Rome", country: "Italy", timezone: "Europe/Rome" },
  { city: "Lisbon", country: "Portugal", timezone: "Europe/Lisbon" },
  { city: "Stockholm", country: "Sweden", timezone: "Europe/Stockholm" },
  { city: "Oslo", country: "Norway", timezone: "Europe/Oslo" },
  { city: "Helsinki", country: "Finland", timezone: "Europe/Helsinki" },
  { city: "Copenhagen", country: "Denmark", timezone: "Europe/Copenhagen" },
  { city: "Dublin", country: "Ireland", timezone: "Europe/Dublin" },
  { city: "Athens", country: "Greece", timezone: "Europe/Athens" },
  { city: "Warsaw", country: "Poland", timezone: "Europe/Warsaw" },
  { city: "Prague", country: "Czech Republic", timezone: "Europe/Prague" },
  { city: "Budapest", country: "Hungary", timezone: "Europe/Budapest" },
  { city: "Bucharest", country: "Romania", timezone: "Europe/Bucharest" },
  { city: "Kiev", country: "Ukraine", timezone: "Europe/Kiev" },
  { city: "Tel Aviv", country: "Israel", timezone: "Asia/Jerusalem" },
  { city: "Tehran", country: "Iran", timezone: "Asia/Tehran" },
  { city: "Karachi", country: "Pakistan", timezone: "Asia/Karachi" },
  { city: "Lahore", country: "Pakistan", timezone: "Asia/Karachi" },
  { city: "Dhaka", country: "Bangladesh", timezone: "Asia/Dhaka" },
  { city: "Kolkata", country: "India", timezone: "Asia/Kolkata" },
  { city: "Chennai", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bengaluru", country: "India", timezone: "Asia/Kolkata" },
  { city: "Hyderabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Pune", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ahmedabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Surat", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jaipur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Lucknow", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kanpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Nagpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Indore", country: "India", timezone: "Asia/Kolkata" },
  { city: "Thane", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhopal", country: "India", timezone: "Asia/Kolkata" },
  { city: "Visakhapatnam", country: "India", timezone: "Asia/Kolkata" },
  { city: "Pimpri-Chinchwad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Patna", country: "India", timezone: "Asia/Kolkata" },
  { city: "Vadodara", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ghaziabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ludhiana", country: "India", timezone: "Asia/Kolkata" },
  { city: "Agra", country: "India", timezone: "Asia/Kolkata" },
  { city: "Nashik", country: "India", timezone: "Asia/Kolkata" },
  { city: "Faridabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Meerut", country: "India", timezone: "Asia/Kolkata" },
  { city: "Rajkot", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kalyan-Dombivli", country: "India", timezone: "Asia/Kolkata" },
  { city: "Vasai-Virar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Varanasi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Srinagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Aurangabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Dhanbad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Amritsar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Navi Mumbai", country: "India", timezone: "Asia/Kolkata" },
  { city: "Allahabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ranchi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Howrah", country: "India", timezone: "Asia/Kolkata" },
  { city: "Coimbatore", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jabalpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Gwalior", country: "India", timezone: "Asia/Kolkata" },
  { city: "Vijayawada", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jodhpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Madurai", country: "India", timezone: "Asia/Kolkata" },
  { city: "Raipur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kota", country: "India", timezone: "Asia/Kolkata" },
  { city: "Guwahati", country: "India", timezone: "Asia/Kolkata" },
  { city: "Chandigarh", country: "India", timezone: "Asia/Kolkata" },
  { city: "Solapur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Hubli-Dharwad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bareilly", country: "India", timezone: "Asia/Kolkata" },
  { city: "Moradabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Mysore", country: "India", timezone: "Asia/Kolkata" },
  { city: "Gurgaon", country: "India", timezone: "Asia/Kolkata" },
  { city: "Aligarh", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jalandhar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Tiruchirappalli", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhubaneswar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Salem", country: "India", timezone: "Asia/Kolkata" },
  { city: "Mira-Bhayandar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Warangal", country: "India", timezone: "Asia/Kolkata" },
  { city: "Guntur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhiwandi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Saharanpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Gorakhpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bikaner", country: "India", timezone: "Asia/Kolkata" },
  { city: "Amravati", country: "India", timezone: "Asia/Kolkata" },
  { city: "Noida", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jamshedpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhilai", country: "India", timezone: "Asia/Kolkata" },
  { city: "Cuttack", country: "India", timezone: "Asia/Kolkata" },
  { city: "Firozabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kochi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Nellore", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhavnagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Dehradun", country: "India", timezone: "Asia/Kolkata" },
  { city: "Durgapur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Asansol", country: "India", timezone: "Asia/Kolkata" },
  { city: "Rourkela", country: "India", timezone: "Asia/Kolkata" },
  { city: "Nanded", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kolhapur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ajmer", country: "India", timezone: "Asia/Kolkata" },
  { city: "Akola", country: "India", timezone: "Asia/Kolkata" },
  { city: "Gulbarga", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jamnagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ujjain", country: "India", timezone: "Asia/Kolkata" },
  { city: "Loni", country: "India", timezone: "Asia/Kolkata" },
  { city: "Siliguri", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jhansi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ulhasnagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jammu", country: "India", timezone: "Asia/Kolkata" },
  { city: "Sangli-Miraj & Kupwad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Mangalore", country: "India", timezone: "Asia/Kolkata" },
  { city: "Erode", country: "India", timezone: "Asia/Kolkata" },
  { city: "Belgaum", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ambattur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Tirunelveli", country: "India", timezone: "Asia/Kolkata" },
  { city: "Malegaon", country: "India", timezone: "Asia/Kolkata" },
  { city: "Gaya", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jalgaon", country: "India", timezone: "Asia/Kolkata" },
  { city: "Udaipur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Maheshtala", country: "India", timezone: "Asia/Kolkata" },
  { city: "Davanagere", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kozhikode", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kurnool", country: "India", timezone: "Asia/Kolkata" },
  { city: "Rajpur Sonarpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Rajahmundry", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bokaro", country: "India", timezone: "Asia/Kolkata" },
  { city: "South Dumdum", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bellary", country: "India", timezone: "Asia/Kolkata" },
  { city: "Patiala", country: "India", timezone: "Asia/Kolkata" },
  { city: "Gopalpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Agartala", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhagalpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Muzaffarnagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhatpara", country: "India", timezone: "Asia/Kolkata" },
  { city: "Panihati", country: "India", timezone: "Asia/Kolkata" },
  { city: "Latur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Dhule", country: "India", timezone: "Asia/Kolkata" },
  { city: "Rohtak", country: "India", timezone: "Asia/Kolkata" },
  { city: "Sagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Korba", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bhilwara", country: "India", timezone: "Asia/Kolkata" },
  { city: "Berhampur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Muzaffarpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ahmednagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Mathura", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kollam", country: "India", timezone: "Asia/Kolkata" },
  { city: "Avadi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kadapa", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kamarhati", country: "India", timezone: "Asia/Kolkata" },
  { city: "Sambalpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bilaspur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Shahjahanpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Satara", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bijapur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Rampur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Shimoga", country: "India", timezone: "Asia/Kolkata" },
  { city: "Chandrapur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Junagadh", country: "India", timezone: "Asia/Kolkata" },
  { city: "Thrissur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Alwar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bardhaman", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kulti", country: "India", timezone: "Asia/Kolkata" },
  { city: "Nizamabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Parbhani", country: "India", timezone: "Asia/Kolkata" },
  { city: "Tumkur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Khammam", country: "India", timezone: "Asia/Kolkata" },
  { city: "Uzhavarkarai", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bihar Sharif", country: "India", timezone: "Asia/Kolkata" },
  { city: "Panipat", country: "India", timezone: "Asia/Kolkata" },
  { city: "Darbhanga", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bally", country: "India", timezone: "Asia/Kolkata" },
  { city: "Aizawl", country: "India", timezone: "Asia/Kolkata" },
  { city: "Dewas", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ichalkaranji", country: "India", timezone: "Asia/Kolkata" },
  { city: "Karnal", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bathinda", country: "India", timezone: "Asia/Kolkata" },
  { city: "Jalna", country: "India", timezone: "Asia/Kolkata" },
  { city: "Eluru", country: "India", timezone: "Asia/Kolkata" },
  { city: "Barasat", country: "India", timezone: "Asia/Kolkata" },
  { city: "Kirari Suleman Nagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Purnia", country: "India", timezone: "Asia/Kolkata" },
  { city: "Satna", country: "India", timezone: "Asia/Kolkata" },
  { city: "Mau", country: "India", timezone: "Asia/Kolkata" },
  { city: "Sonipat", country: "India", timezone: "Asia/Kolkata" },
  { city: "Farrukhabad", country: "India", timezone: "Asia/Kolkata" },
  { city: "Sagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Durg", country: "India", timezone: "Asia/Kolkata" },
  { city: "Imphal", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ratlam", country: "India", timezone: "Asia/Kolkata" },
  { city: "Hapur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Arrah", country: "India", timezone: "Asia/Kolkata" },
  { city: "Anantapur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Karimnagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Etawah", country: "India", timezone: "Asia/Kolkata" },
  { city: "Ambernath", country: "India", timezone: "Asia/Kolkata" },
  { city: "North Dumdum", country: "India", timezone: "Asia/Kolkata" },
  { city: "Bharatpur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Begusarai", country: "India", timezone: "Asia/Kolkata" },
  { city: "New Delhi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Gandhidham", country: "India", timezone: "Asia/Kolkata" },
  { city: "Baranagar", country: "India", timezone: "Asia/Kolkata" },
  { city: "Tiruppur", country: "India", timezone: "Asia/Kolkata" },
  { city: "Morena", country: "India", timezone: "Asia/Kolkata" },
  { city: "Morbi", country: "India", timezone: "Asia/Kolkata" },
  { city: "Mormugao", country: "India", timezone: "Asia/Kolkata" },
  { city: "Moreno Valley", country: "United States", timezone: "America/Los_Angeles" },
];
