name: CI

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      BETTER_AUTH_SECRET: 'mock-secret-for-ci-tests-32chars'
      DATABASE_URL: 'postgresql://mock:mock@localhost:5432/mock'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Linter
        run: bun run lint

      - name: Check Formatting
        run: bun run format:check

      - name: Build Project
        run: bun run build

      - name: Run Unit Tests
        run: bun run test

      - name: Install Playwright Browsers
        run: bun x playwright install --with-deps

      - name: Run E2E Tests
        run: bun run test:e2e
